### ISSUE TITLE
The game crashes at startup

### ISSUE THREAD

**Issue by Omgise** [jss2a98aj/NotFine#25]
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15030994/fml-client-latest.log)
[crash-2024-04-19_06.03.30-client.txt](https://github.com/jss2a98aj/NotFine/files/15031000/crash-2024-04-19_06.03.30-client.txt)

**Comment by jss2a98aj** [comment]
Can you upload the full log? There are likely Mixin conflicts with another mod causing it, but I cannot see those from the crash report alone.

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15039894/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/jss2a98aj/NotFine/files/15039895/fml-junk-earlystartup.log)
[latest.log](https://github.com/jss2a98aj/NotFine/files/15039897/latest.log)

**Comment by jss2a98aj** [comment]
Setting
`B:RENDER_HOOK_COMPAT_MODE=true`
and
`B:OCCLUSION_TWEAKS=false`
in FalseTweaks should fix that crash.

I do plan to fix compatibility with FalseTweaks occlusion tweaks at some point.

**Comment by Omgise** [comment]
The game still crashes after the setup
[fml-junk-earlystartup.log](https://github.com/jss2a98aj/NotFine/files/15040380/fml-junk-earlystartup.log)
[latest.log](https://github.com/jss2a98aj/NotFine/files/15040381/latest.log)
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15040379/fml-client-latest.log)

**Comment by jss2a98aj** [comment]
I am still seeing `Redirect conflict. Skipping mixins.falsetweaks.json:client.occlusion.RenderGlobalMixin from mod falsetweaks` which should not be the case with it off. Unless something is forcing it back on at runtime I don't think `B:OCCLUSION_TWEAKS=false` was set before that launch.

**Comment by Omgise** [comment]
But on entering the world there is a new crash
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15040837/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/jss2a98aj/NotFine/files/15040840/fml-junk-earlystartup.log)
[latest.log](https://github.com/jss2a98aj/NotFine/files/15040841/latest.log)

**Comment by jss2a98aj** [comment]
Can you try setting `B:fixRenderersWorldLeak=false` in Hodgepodge?

**Comment by Omgise** [comment]
[fml-junk-earlystartup.log](https://github.com/jss2a98aj/NotFine/files/15046051/fml-junk-earlystartup.log)
[latest.log](https://github.com/jss2a98aj/NotFine/files/15046052/latest.log)
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15046053/fml-client-latest.log)

**Comment by jss2a98aj** [comment]
Hodgepodge `fixRenderersWorldLeak` was just getting caught in the exception and is fine to turn back on. The crash does involve the particle EffectRenderer though.

The only new thing making changes to the EffectRenderer is the MCPatcher Forge better skies module. Can you try turning it off in the config?

**Comment by Omgise** [comment]
Closing the better skies module worked and there are no crashes now.
![image](https://github.com/jss2a98aj/NotFine/assets/106000018/13389957-827c-447c-9c65-6381db7a7065)

**Comment by Omgise** [comment]
But after a while, the game crashed again with a white screen
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15048417/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/jss2a98aj/NotFine/files/15048418/fml-junk-earlystartup.log)
[latest.log](https://github.com/jss2a98aj/NotFine/files/15048419/latest.log)

**Comment by jss2a98aj** [comment]
There are a lot of mods applying mixins to the things in the stacktrace. It may not be related to NotFine, but it does have some mixin presence in the stacktrace as well. If you can determine the minimum mods needed to replicate the crash it would make it much easier to debug and hopefully fix.

**Comment by Omgise** [comment]
I found the specific crash mod combination.
![image](https://github.com/jss2a98aj/NotFine/assets/106000018/a8c8cdac-306c-4d5e-823d-9fb9aedd5230)
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15063271/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/jss2a98aj/NotFine/files/15063272/fml-junk-earlystartup.log)
[latest.log](https://github.com/jss2a98aj/NotFine/files/15063273/latest.log)

**Comment by jss2a98aj** [comment]
Thank you for narrowing it down. I should be able to find the cause of that issue now.

There is a potentially unrelated problem that I am seeing in this most recent log. FalsePatternLib is failing to open the jar file for a dependency lumina requests. It may be having issues with double width characters in the file path, as it is showing `D:/%e6%88%91%e7%9a%84%e4%b8%96%e7%95%8c/` instead of `D:/我的世界/` in part of an error print.

**Comment by Omgise** [comment]
notfine and the latest EFR candidate crashed, and I suspect that notfine's ctm connection texture is causing the problem
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15396599/fml-client-latest.log)

**Comment by jss2a98aj** [comment]
That is something that will be fixed soon, either in EFR or here.

**Comment by jss2a98aj** [comment]
The next EFR RC should work with the latest release.

**Comment by Roadhog360** [comment]
Actually it should work now, my glass pane mixin reqrite addresses the crash fron NF's end

**Comment by Omgise** [comment]
Looks like there's been a weird rendering error

https://github.com/jss2a98aj/NotFine/assets/106000018/b122cbe6-68a0-4449-89c8-9af143bd27ab

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/jss2a98aj/NotFine/files/15410864/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/jss2a98aj/NotFine/files/15410865/fml-junk-earlystartup.log)
[latest.log](https://github.com/jss2a98aj/NotFine/files/15410866/latest.log)

**Comment by Roadhog360** [comment]
Separate issue, make a new report please
